# Generated by Django 6.0.6 on 2026-06-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('logo_file', models.ImageField(blank=True, null=True, upload_to='sponsors/', verbose_name='Логотип: Загрузить файл')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='Логотип: Или вставить ссылку')),
                ('link', models.URLField(blank=True, default='#', null=True, verbose_name='Ссылка на сайт партнера (необязательно)')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='university_logo',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='university_logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип: Загрузить файл (PNG/SVG)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='university_logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Логотип: Или вставить ссылку (URL)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео: Или вставить ссылку (Прямой MP4 или YouTube Embed)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео: Загрузить файл (MP4)'),
        ),
    ]
