# Generated by Django 6.0.6 on 2026-06-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_sponsor_remove_siteconfiguration_university_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='campus/', verbose_name='Фото кампуса 1'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='campus/', verbose_name='Фото кампуса 2'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='campus/', verbose_name='Фото кампуса 3'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='university_logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип: Загрузить файл'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='university_logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Логотип: Ссылка'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео: Или вставить ссылку'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='link',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='Ссылка на сайт партнера'),
        ),
    ]
