# Generated by Django 6.0.6 on 2026-06-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категория (например: Общежитие, Гранты)')),
                ('content', models.TextField(verbose_name='Текст документа для ИИ')),
            ],
        ),
    ]
