# Generated by Django 6.0.6 on 2026-06-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Шифр специальности')),
                ('name', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('min_score', models.IntegerField(verbose_name='Минимальный проходной балл')),
                ('allocated_grants', models.IntegerField(default=0, verbose_name='Количество выделенных грантов')),
            ],
        ),
    ]
